version: '3'
services:
  lrs:
      image: noampolak/adl_lrs
      container_name: web-lrs
      command: manage runserver 0.0.0.0:80
      ports:
          - "8080:80"
      networks:
        - back-tier
        - front-tier

  postgres:
    image: postgres:alpine
    container_name: postgres-lrs
    environment:
      POSTGRES_PASSWORD: lrs
      POSTGRES_USER: lrs
      POSTGRES_DB: lrs
    ports:
      - "8432:5432"
    networks:
      - back-tier
  rabbitmq:
      image: rabbitmq:3.8
      privileged: true
      container_name: rabbit-lrs
      environment:
        RABBITMQ_DEFAULT_USER: user-lrs
        RABBITMQ_DEFAULT_PASS: lrs-password
        RABBITMQ_DEFAULT_VHOST: lrs-vhost
      ports:
        - "15672:15672"
      networks:
        - back-tier
        - front-tier
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
